---
title: "Cowichan River Water Quality dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyr)
library(lubridate)
library(ggplot2)
library(dplyr)
library(plotly)
```



```{r}

#pH Data
data<-read.csv("pHMaster.csv")

#Data Formatting----
data<- rename(data, "70.2 Trestle" = X70.2.Trestle)

data$Date = as.POSIXct(data$Date, format = "%m/%d/%Y %H:%M")

pHlong <- data %>% 
  pivot_longer(
    cols = 2:6, 
    names_to = "site",
    values_to = "pH"
  )
pHlong$site<-factor(pHlong$site,levels=c("Saysells","70.2 Trestle","HSB", "US_JUB","DS_JUB"))

#keep the rows where pH is not missing
pHlong_no_NA <- filter(pHlong, pH != "NA" & site != 'na')
#-------------------------------------------------------------------------------------------------Temp data
tempdata<-read.csv("temp.csv")

#Data Formatting----
tempdata<- rename(tempdata, "70.2 Trestle" = X70.2.Trestle)

tempdata$Date = as.POSIXct(tempdata$Date, format = "%m/%d/%Y %H:%M")

tempdatalong <- tempdata %>% 
  pivot_longer(
    cols = 2:6, 
    names_to = "site",
    values_to = "temp"
  )

tempdatalong$site<-factor(tempdatalong$site,levels=c("Saysells","70.2 Trestle","HSB", "US.JUB","DS.JUB"))

#keep the rows where pH is not missing
tempdatalong_no_NA <- filter(tempdatalong, temp != "NA" & site != 'na')
#-------------------------------------------------------------------------------------------------DO data
DOdata<-read.csv("DOmaster.csv")

DOdata$Date = as.POSIXct(DOdata$Date, format = "%m/%d/%Y %H:%M")

DOdata$site<-factor(DOdata$site,levels=c("Saysells","70.2 Trestle","HSB"))

DOdata <- filter(DOdata, DO != "NA" & site != 'na')


```

pH {data-orientation=rows}
=====================================

Row {data-height=600}
-------------------------------------

### pH values 2024

```{r}


pHPlot<- ggplot(data=pHlong_no_NA,aes(x=Date, y=pH,
                     colour=site))+
  geom_point(position=position_jitter(h=0.1, w=0.1),
             shape = 21, alpha = 0.5, size = 0.5)+
  scale_x_datetime(date_labels= "%e-%b", date_breaks="5 days")+
  xlab("")+
  ylab("pH")+
  theme_classic()
ggplotly(pHPlot)
```

Water temperature
=====================================  
Row {data-height=600}
-------------------------------------

### Temperature values 2024

```{r}


TempPlot<- ggplot(data=tempdatalong_no_NA,aes(x=Date, y=temp,
                     colour=site))+
  geom_point(position=position_jitter(h=0.1, w=0.1),
             shape = 21, alpha = 0.5, size = 0.5)+
  scale_x_datetime(date_labels= "%e-%b", date_breaks="5 days")+
  xlab("")+
  ylab("Temp(C)")+
  theme_classic()
ggplotly(TempPlot)
```

Dissolved Oxygen (mg/l)
===================================== 
Row {data-height=600}
-------------------------------------

### DO values 2024

```{r}


DOPlot<- ggplot(data=DOdata,aes(x=Date, y=DO,
                     colour=site))+
  geom_point(position=position_jitter(h=0.1, w=0.1),
             shape = 21, alpha = 0.5, size = 0.5)+
  scale_x_datetime(date_labels= "%e-%b", date_breaks="5 days")+
  xlab("")+
  ylab("DO")+
  theme_classic()
ggplotly(DOPlot)
```